version: "3.9"

services:
    react:
        build: .
        container_name: react_app
        volumes:
            - .:/app
        ports:
            - "3000:3000"
        command: npm run dev

    json-server:
        image: node:20-alpine
        working_dir: /app
        volumes:
            - .:/app
        command: npx json-server --watch db.json --host 0.0.0.0 --port 4000
        ports:
            - "4000:4000"
